language: groovy
dist: precise

jdk:
  - openjdk7
  - oraclejdk8

env:
  global:
  - GRADLE_OPTS="-Xmx1024m"

script:
  - ./gradlew check uploadArchives --full-stacktrace
  - cd samples/example && ./gradlew clean webResourceCompile --full-stacktrace && cd ../../

after_success:
  - ./gradlew coveralls --full-stacktrace
