language: groovy
sudo: false
dist: precise

jdk:
  - openjdk7
  - oraclejdk8

env:
  global:
  - JAVA_OPTS="-Dhttps.protocols=SSLv3,TLSv1,TLSv1.1,TLSv1.2"
  - GRADLE_OPTS="-Xmx1024m"

script:
  - ./gradlew check uploadArchives --full-stacktrace
  - cd samples/example && ./gradlew clean webResourceCompile --full-stacktrace && cd ../../

after_success:
  - ./gradlew coveralls --full-stacktrace
